### ISSUE TITLE
_.reduceRight equivalent for Lua

### ISSUE THREAD

**Issue by darmie** [mirven/underscore.lua#19]
Hi, I am trying to port an existing JS framework to Lua, the framework uses underscore.js in most  parts, I stumbled upon `_.reduceRight` but it's implementation is not found at http://mirven.github.com/underscore.lua

**Comment by tst2005** [comment]
Hello,

[underscore.lua](https://github.com/mirven/underscore.lua/) seems abandonned.

Take a look at [Moses](https://github.com/Yonaba/Moses) that has a [reduceRight](http://yonaba.github.io/Moses/doc/#mapReduceRight).
I hope that should help you.

Regards,

**Comment by darmie** [comment]
Thank you!
